services:
  - type: web
    name: calendar-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    plan: free
    autoDeploy: true

  - type: static
    name: calendar-frontend
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: build
    plan: free
    autoDeploy: true
